spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: post-web
          uri: http://localhost:9092
          predicates:
            - Path=/post/**
            - Method=GET,POST,PUT,DELETE
          filters:
            - name: CircuitBreaker
              args:
                name: myCircuitBreaker
                fallbackUri: forward:/fallback/post-fallback
        - id: post-web-retry
          uri: http://localhost:9092
          predicates:
            - Path=/post/retry
          filters:
            - name: Retry
              args:
                # Số lần thử lại khi gặp lỗi
                retries: 5
                # Các mã trạng thái HTTP mà yêu cầu sẽ được thử lại
                statuses: REQUEST_TIMEOUT, SERVICE_UNAVAILABLE
                # Phương thức HTTP sẽ được thử lại
                methods: GET
                backoff:
                  # Thời gian chờ ban đầu trước khi thử lại lần đầu tiên
                  firstBackoff: 3s
                  # Thời gian chờ tối đa trước khi thử lại
                  maxBackoff: 5s
                  # Hệ số nhân cho thời gian chờ trước mỗi lần thử lại
                  factor: 2
                  # Nếu đặt là true, thời gian chờ của lần thử lại tiếp theo sẽ được tính dựa trên thời gian chờ của lần thử lại trước đó
                  basedOnPreviousValue: false

# Nhật kí
logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway:
            route:
              RouteDefinitionLocator: INFO
            TRACE: TRACE
server:
  port: 9090